#!/usr/bin/env bash
#
#   install - This script installs universal compilation tool for
#   different programming languages
#   Copyright (c) 2012-2014 Shubham Chaudhary <me@shubhamchaudhary.in>
#
#   This file is a part of Universal.
#
#   Universal is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   Universal is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with Universal.  If not, see <http://www.gnu.org/licenses/>.
#


#clear
INSTALL_DIR="~/.local/bin"
INSTALL_DIR="/usr/bin"

FILENAME_UNI="universal"
FILENAME_FOLLOW="follow"
FULL_FILENAME_UNI="universal.sh"
FULL_FILENAME_FOLLOW="follow.sh"

FILE_UNI="$INSTALL_DIR/${FILENAME_UNI}"
FILE_FOLLOW="$INSTALL_DIR/${FILENAME_FOLLOW}"

CURRENT_DIR=`pwd`
CUR_FILE_UNI="$CURRENT_DIR/${FILENAME_UNI}.pl"
CUR_FILE_FOLLOW="$CURRENT_DIR/${FILENAME_FOLLOW}.sh"

echo    #newline

#Show Usage & Help
helpInstall(){ 
    #echo "# # # # # # # # # # # # # # # # # # # # # # # # # # # #"
    echo "  ###################################################################"
    echo "  #      + + + Universal Compiler Installation Help + + +       (c) #"
    echo "  #                                                                 #"
    echo "  # USAGE:  Just type this command to execute installation process: #" 
    echo "  #   \`./install\`                                                   #"
    echo "  #         This'll install Universal Compiler in it's proper place #"
    echo "  #                                                                 #"
    echo "  # Warning: Please don't forget that installation requires 'sudo'  #"
    echo "  #          permissions. Provide password when asked or run as su. #"
    echo "  #                                                                 #"
    echo "  # Note   : If install file does not have execution permission you #"
    echo "  #          should execute this command first                      #"
    echo "  #   \`sudo chmod 777 install universal.pl\`                         #"
    echo "  #                                                                 #"
    echo "  # To Uninstall previous installations type:                       #"
    echo "  #   \`./install --uninstall\`                                       #"
    echo "  #                                                                 #"
    echo "  ###################################################################"
    echo "  # Program: Universal Compiler - Programming made easy             #"
    echo "  # Author : Shubham Chaudhary                                      #"
    echo "  ###################################################################"
    #echo "# # # # # # # # # # # # # # # # # # # # # # # # # # # #"
    echo    #newline
}

if test "$1" == "--help"
then
    helpInstall
    exit 0
fi

if test "$1" == "--uninstall"
then
    echo "About to uninstall Universal Compiler Tool"
    echo "Are you sure ? <Y/n>"
    read sure
    if test sure == 'Y'
    then
        sudo rm "$FILE_UNI" "$FILE_FOLLOW"
        sudo rm "$INSTALL_DIR/u" "$INSTALL_DIR/c" "$INSTALL_DIR/f"
        sudo rm "/usr/local/bin/$FILENAME_UNI"
        sudo rm "/usr/local/bin/$FULL_FILENAME_UNI"
        sudo rm "/usr/local/bin/$FILENAME_FOLLOW"
        sudo rm "/usr/local/bin/$FULL_FILENAME_FOLLOW"
        exit 0
    fi
fi

echo "You can get help or uninstall using : "
echo "./install --help"
echo "./install --uninstall"
echo    #newline

#echo "To continue installation hit Enter"
#read

echo    #newline
if [ -f "/usr/local/bin/chaudhary.sh" ]; then
    echo -n "Removing older version: ";
    sudo rm -vf "/usr/local/bin/chaudhary.sh";
fi
if [ -f "/usr/local/bin/universal.sh" ]; then
    echo -n "Removing older version: ";
    sudo rm -vf "/usr/local/bin/universal.sh";
fi

echo " * * * Installing Universal Compilation Tool * * *"
echo "  ############################################################"
echo "  # Tool Name :  Universal Compiler - Programming made easy  #"
echo "  ############################################################"
## Install Universal
if [ ! -f "$FILE_UNI" ] ; then
    echo " * * * Copying Files * * *"
elif [ "$FILE_UNI" -ot "$CUR_FILE_UNI" ]; then
    echo "Older Version of universal found and will be updated now"
fi
sudo cp -pv "$CUR_FILE_UNI" "$FILE_UNI";

# Same for Follow
if [ ! -f "$FILE_UNI" ] ; then
    echo " * * * Copying Files * * *"
elif [ "$FILE_UNI" -ot "$CUR_FILE_UNI" ]; then
    echo "Older Version of follow found and will be updated now"
fi
sudo cp -pv "$CUR_FILE_FOLLOW" "$FILE_FOLLOW";

#echo "Create Shortcuts? <y/n>"
#read shortcut
#shortcut="y"
#if [ "$shortcut" == "y" ]; then
#    if [ ! -f ~/.bash_aliases ]; then
#        touch ~/.bash_aliases
#    fi
#    echo "Appending in ~/.bash_aliases"
#    echo "alias c='/usr/local/bin/universal.sh'" >> ~/.bash_aliases
    echo "Creating shortcuts links"
    sudo cp -sf "$FILE_UNI" "/usr/bin/u"
    echo "Use u as shortcut for universal"
    sudo cp -sf "$FILE_FOLLOW" "$INSTALL_DIR/f"
    echo "Use f as shortcut for follow"
#fi
# del="y"
# echo -n "Delete files? <y/n>"
# read del
# if [ "$del" == "y" ]; then
#     rm -ivf universal.pl universal.sh install README.md
# fi
echo ; #newline
echo "Use update option --update or -u to get latest version";
echo "Copy/Paste ==> u -u"
echo "or Copy/Paste ==> universal -u"
